{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "datePublic": "2012-04-14T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2013-01-29T10:00:00",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "name": "USN-1615-1",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_UBUNTU"
                    ],
                    "url": "http://www.ubuntu.com/usn/USN-1615-1"
                },
                {
                    "name": "51087",
                    "tags": [
                        "third-party-advisory",
                        "x_refsource_SECUNIA"
                    ],
                    "url": "http://secunia.com/advisories/51087"
                },
                {
                    "name": "USN-1616-1",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_UBUNTU"
                    ],
                    "url": "http://www.ubuntu.com/usn/USN-1616-1"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "http://bugs.python.org/issue14579"
                },
                {
                    "name": "51089",
                    "tags": [
                        "third-party-advisory",
                        "x_refsource_SECUNIA"
                    ],
                    "url": "http://secunia.com/advisories/51089"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389"
                },
                {
                    "name": "[oss-security] 20120425 Re: CVE Request: Python 3.2/3.3 utf-16 decoder unicode_decode_call_errorhandler aligned_end is not updated",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://www.openwall.com/lists/oss-security/2012/04/25/4"
                },
                {
                    "name": "[oss-security] 20120425 CVE Request: Python 3.2/3.3 utf-16 decoder unicode_decode_call_errorhandler aligned_end is not updated",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://www.openwall.com/lists/oss-security/2012/04/25/2"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2012-2135",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "USN-1615-1",
                            "refsource": "UBUNTU",
                            "url": "http://www.ubuntu.com/usn/USN-1615-1"
                        },
                        {
                            "name": "51087",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/51087"
                        },
                        {
                            "name": "USN-1616-1",
                            "refsource": "UBUNTU",
                            "url": "http://www.ubuntu.com/usn/USN-1616-1"
                        },
                        {
                            "name": "http://bugs.python.org/issue14579",
                            "refsource": "MISC",
                            "url": "http://bugs.python.org/issue14579"
                        },
                        {
                            "name": "51089",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/51089"
                        },
                        {
                            "name": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389",
                            "refsource": "MISC",
                            "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389"
                        },
                        {
                            "name": "[oss-security] 20120425 Re: CVE Request: Python 3.2/3.3 utf-16 decoder unicode_decode_call_errorhandler aligned_end is not updated",
                            "refsource": "MLIST",
                            "url": "http://www.openwall.com/lists/oss-security/2012/04/25/4"
                        },
                        {
                            "name": "[oss-security] 20120425 CVE Request: Python 3.2/3.3 utf-16 decoder unicode_decode_call_errorhandler aligned_end is not updated",
                            "refsource": "MLIST",
                            "url": "http://www.openwall.com/lists/oss-security/2012/04/25/2"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2012-2135",
        "datePublished": "2012-08-14T22:00:00",
        "dateReserved": "2012-04-04T00:00:00",
        "dateUpdated": "2013-01-29T10:00:00",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}