{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "datePublic": "2014-08-20T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "The core.urlresolvers.reverse function in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 does not properly validate URLs, which allows remote attackers to conduct phishing attacks via a // (slash slash) in a URL, which triggers a scheme-relative URL to be generated."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2017-01-04T17:57:01",
                "orgId": "79363d38-fa19-49d1-9214-5f28da3f3ac5",
                "shortName": "debian"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://www.djangoproject.com/weblog/2014/aug/20/security/"
                },
                {
                    "name": "69425",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_BID"
                    ],
                    "url": "http://www.securityfocus.com/bid/69425"
                },
                {
                    "name": "61276",
                    "tags": [
                        "third-party-advisory",
                        "x_refsource_SECUNIA"
                    ],
                    "url": "http://secunia.com/advisories/61276"
                },
                {
                    "name": "61281",
                    "tags": [
                        "third-party-advisory",
                        "x_refsource_SECUNIA"
                    ],
                    "url": "http://secunia.com/advisories/61281"
                },
                {
                    "name": "openSUSE-SU-2014:1132",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_SUSE"
                    ],
                    "url": "http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html"
                },
                {
                    "name": "DSA-3010",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_DEBIAN"
                    ],
                    "url": "http://www.debian.org/security/2014/dsa-3010"
                },
                {
                    "name": "59782",
                    "tags": [
                        "third-party-advisory",
                        "x_refsource_SECUNIA"
                    ],
                    "url": "http://secunia.com/advisories/59782"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "security@debian.org",
                    "ID": "CVE-2014-0480",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "The core.urlresolvers.reverse function in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 does not properly validate URLs, which allows remote attackers to conduct phishing attacks via a // (slash slash) in a URL, which triggers a scheme-relative URL to be generated."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://www.djangoproject.com/weblog/2014/aug/20/security/",
                            "refsource": "CONFIRM",
                            "url": "https://www.djangoproject.com/weblog/2014/aug/20/security/"
                        },
                        {
                            "name": "69425",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/69425"
                        },
                        {
                            "name": "61276",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/61276"
                        },
                        {
                            "name": "61281",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/61281"
                        },
                        {
                            "name": "openSUSE-SU-2014:1132",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html"
                        },
                        {
                            "name": "DSA-3010",
                            "refsource": "DEBIAN",
                            "url": "http://www.debian.org/security/2014/dsa-3010"
                        },
                        {
                            "name": "59782",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/59782"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "79363d38-fa19-49d1-9214-5f28da3f3ac5",
        "assignerShortName": "debian",
        "cveId": "CVE-2014-0480",
        "datePublished": "2014-08-26T14:00:00",
        "dateReserved": "2013-12-19T00:00:00",
        "dateUpdated": "2017-01-04T17:57:01",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}