{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "tensorflow",
                    "vendor": "tensorflow",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "< 2.1.4"
                        },
                        {
                            "status": "affected",
                            "version": ">= 2.2.0, < 2.2.3"
                        },
                        {
                            "status": "affected",
                            "version": ">= 2.3.0, < 2.3.3"
                        },
                        {
                            "status": "affected",
                            "version": ">= 2.4.0, < 2.4.2"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "TensorFlow is an end-to-end open source platform for machine learning. An attacker can cause a denial of service by exploiting a `CHECK`-failure coming from the implementation of `tf.raw_ops.RFFT`. Eigen code operating on an empty matrix can trigger on an assertion and will cause program termination. The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range."
                }
            ],
            "metrics": [
                {
                    "cvssV3_1": {
                        "attackComplexity": "HIGH",
                        "attackVector": "LOCAL",
                        "availabilityImpact": "LOW",
                        "baseScore": 2.5,
                        "baseSeverity": "LOW",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "LOW",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:L",
                        "version": "3.1"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-617",
                            "description": "CWE-617: Reachable Assertion",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-05-14T19:17:06",
                "orgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
                "shortName": "GitHub_M"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-ph87-fvjr-v33w"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://github.com/tensorflow/tensorflow/commit/31bd5026304677faa8a0b77602c6154171b9aec1"
                }
            ],
            "source": {
                "advisory": "GHSA-ph87-fvjr-v33w",
                "discovery": "UNKNOWN"
            },
            "title": "CHECK-fail in `tf.raw_ops.RFFT`",
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "security-advisories@github.com",
                    "ID": "CVE-2021-29563",
                    "STATE": "PUBLIC",
                    "TITLE": "CHECK-fail in `tf.raw_ops.RFFT`"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "tensorflow",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "< 2.1.4"
                                                    },
                                                    {
                                                        "version_value": ">= 2.2.0, < 2.2.3"
                                                    },
                                                    {
                                                        "version_value": ">= 2.3.0, < 2.3.3"
                                                    },
                                                    {
                                                        "version_value": ">= 2.4.0, < 2.4.2"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "tensorflow"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "TensorFlow is an end-to-end open source platform for machine learning. An attacker can cause a denial of service by exploiting a `CHECK`-failure coming from the implementation of `tf.raw_ops.RFFT`. Eigen code operating on an empty matrix can trigger on an assertion and will cause program termination. The fix will be included in TensorFlow 2.5.0. We will also cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4, as these are also affected and still in supported range."
                        }
                    ]
                },
                "impact": {
                    "cvss": {
                        "attackComplexity": "HIGH",
                        "attackVector": "LOCAL",
                        "availabilityImpact": "LOW",
                        "baseScore": 2.5,
                        "baseSeverity": "LOW",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "LOW",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:L",
                        "version": "3.1"
                    }
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "CWE-617: Reachable Assertion"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-ph87-fvjr-v33w",
                            "refsource": "CONFIRM",
                            "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-ph87-fvjr-v33w"
                        },
                        {
                            "name": "https://github.com/tensorflow/tensorflow/commit/31bd5026304677faa8a0b77602c6154171b9aec1",
                            "refsource": "MISC",
                            "url": "https://github.com/tensorflow/tensorflow/commit/31bd5026304677faa8a0b77602c6154171b9aec1"
                        }
                    ]
                },
                "source": {
                    "advisory": "GHSA-ph87-fvjr-v33w",
                    "discovery": "UNKNOWN"
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
        "assignerShortName": "GitHub_M",
        "cveId": "CVE-2021-29563",
        "datePublished": "2021-05-14T19:17:07",
        "dateReserved": "2021-03-30T00:00:00",
        "dateUpdated": "2021-05-14T19:17:06",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}