{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "datePublic": "2014-05-14T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "The django.util.http.is_safe_url function in Django 1.4 before 1.4.13, 1.5 before 1.5.8, 1.6 before 1.6.5, and 1.7 before 1.7b4 does not properly validate URLs, which allows remote attackers to conduct open redirect attacks via a malformed URL, as demonstrated by \"http:\\\\\\djangoproject.com.\""
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2017-01-04T17:57:01",
                "orgId": "79363d38-fa19-49d1-9214-5f28da3f3ac5",
                "shortName": "debian"
            },
            "references": [
                {
                    "name": "61281",
                    "tags": [
                        "third-party-advisory",
                        "x_refsource_SECUNIA"
                    ],
                    "url": "http://secunia.com/advisories/61281"
                },
                {
                    "name": "DSA-2934",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_DEBIAN"
                    ],
                    "url": "http://www.debian.org/security/2014/dsa-2934"
                },
                {
                    "name": "USN-2212-1",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_UBUNTU"
                    ],
                    "url": "http://ubuntu.com/usn/usn-2212-1"
                },
                {
                    "name": "67410",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_BID"
                    ],
                    "url": "http://www.securityfocus.com/bid/67410"
                },
                {
                    "name": "openSUSE-SU-2014:1132",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_SUSE"
                    ],
                    "url": "http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html"
                },
                {
                    "name": "[oss-security] 20140514 Re: CVE Reuest: Django: Malformed URLs from user input incorrectly validated",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://www.openwall.com/lists/oss-security/2014/05/15/3"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://www.djangoproject.com/weblog/2014/may/14/security-releases-issued/"
                },
                {
                    "name": "[oss-security] 20140514 CVE Reuest: Django: Malformed URLs from user input incorrectly validated",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "http://www.openwall.com/lists/oss-security/2014/05/14/10"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "security@debian.org",
                    "ID": "CVE-2014-3730",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "The django.util.http.is_safe_url function in Django 1.4 before 1.4.13, 1.5 before 1.5.8, 1.6 before 1.6.5, and 1.7 before 1.7b4 does not properly validate URLs, which allows remote attackers to conduct open redirect attacks via a malformed URL, as demonstrated by \"http:\\\\\\djangoproject.com.\""
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "61281",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/61281"
                        },
                        {
                            "name": "DSA-2934",
                            "refsource": "DEBIAN",
                            "url": "http://www.debian.org/security/2014/dsa-2934"
                        },
                        {
                            "name": "USN-2212-1",
                            "refsource": "UBUNTU",
                            "url": "http://ubuntu.com/usn/usn-2212-1"
                        },
                        {
                            "name": "67410",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/67410"
                        },
                        {
                            "name": "openSUSE-SU-2014:1132",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html"
                        },
                        {
                            "name": "[oss-security] 20140514 Re: CVE Reuest: Django: Malformed URLs from user input incorrectly validated",
                            "refsource": "MLIST",
                            "url": "http://www.openwall.com/lists/oss-security/2014/05/15/3"
                        },
                        {
                            "name": "https://www.djangoproject.com/weblog/2014/may/14/security-releases-issued/",
                            "refsource": "CONFIRM",
                            "url": "https://www.djangoproject.com/weblog/2014/may/14/security-releases-issued/"
                        },
                        {
                            "name": "[oss-security] 20140514 CVE Reuest: Django: Malformed URLs from user input incorrectly validated",
                            "refsource": "MLIST",
                            "url": "http://www.openwall.com/lists/oss-security/2014/05/14/10"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "79363d38-fa19-49d1-9214-5f28da3f3ac5",
        "assignerShortName": "debian",
        "cveId": "CVE-2014-3730",
        "datePublished": "2014-05-16T15:00:00",
        "dateReserved": "2014-05-14T00:00:00",
        "dateUpdated": "2017-01-04T17:57:01",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}