{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "python",
                    "vendor": "[UNKNOWN]",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "python 2.7.15"
                        },
                        {
                            "status": "affected",
                            "version": "python 3.4.9"
                        },
                        {
                            "status": "affected",
                            "version": "python 3.5.6"
                        },
                        {
                            "status": "affected",
                            "version": "python 3.7.0"
                        }
                    ]
                }
            ],
            "datePublic": "2018-03-14T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "python before versions 2.7.15, 3.4.9, 3.5.6rc1, 3.6.5rc1 and 3.7.0 is vulnerable to catastrophic backtracking in pop3lib's apop() method. An attacker could use this flaw to cause denial of service."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "LOW",
                        "baseScore": 4.3,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "NONE",
                        "scope": "UNCHANGED",
                        "userInteraction": "REQUIRED",
                        "vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-20",
                            "description": "CWE-20",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2020-01-21T21:06:22",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "name": "DSA-4306",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_DEBIAN"
                    ],
                    "url": "https://www.debian.org/security/2018/dsa-4306"
                },
                {
                    "name": "1042001",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_SECTRACK"
                    ],
                    "url": "http://www.securitytracker.com/id/1042001"
                },
                {
                    "name": "[debian-lts-announce] 20180926 [SECURITY] [DLA 1520-1] python3.4 security update",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "https://lists.debian.org/debian-lts-announce/2018/09/msg00031.html"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://bugs.python.org/issue32981"
                },
                {
                    "name": "USN-3817-2",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_UBUNTU"
                    ],
                    "url": "https://usn.ubuntu.com/3817-2/"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-release-candidate-1"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-6-release-candidate-1"
                },
                {
                    "name": "RHSA-2018:3505",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2018:3505"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1060"
                },
                {
                    "name": "RHSA-2018:3041",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2018:3041"
                },
                {
                    "name": "DSA-4307",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_DEBIAN"
                    ],
                    "url": "https://www.debian.org/security/2018/dsa-4307"
                },
                {
                    "name": "USN-3817-1",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_UBUNTU"
                    ],
                    "url": "https://usn.ubuntu.com/3817-1/"
                },
                {
                    "name": "[debian-lts-announce] 20180925 [SECURITY] [DLA 1519-1] python2.7 security update",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "https://lists.debian.org/debian-lts-announce/2018/09/msg00030.html"
                },
                {
                    "name": "FEDORA-2019-6e1938a3c5",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_FEDORA"
                    ],
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JSKPGPZQNTAULHW4UH63KGOOUIDE4RRB/"
                },
                {
                    "name": "FEDORA-2019-cf725dd20b",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_FEDORA"
                    ],
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/AEZ5IQT7OF7Q2NCGIVABOWYGKO7YU3NJ/"
                },
                {
                    "name": "FEDORA-2019-51f1e08207",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_FEDORA"
                    ],
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/46PVWY5LFP4BRPG3BVQ5QEEFYBVEXHCK/"
                },
                {
                    "name": "RHBA-2019:0327",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHBA-2019:0327"
                },
                {
                    "name": "RHSA-2019:1260",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2019:1260"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://support.hpe.com/hpsc/doc/public/display?docLocale=en_US&docId=emr_na-hpesbst03951en_us"
                },
                {
                    "name": "RHSA-2019:3725",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2019:3725"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://www.oracle.com/security-alerts/cpujan2020.html"
                },
                {
                    "name": "openSUSE-SU-2020:0086",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_SUSE"
                    ],
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2018-1060",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "python",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "python 2.7.15"
                                                    },
                                                    {
                                                        "version_value": "python 3.4.9"
                                                    },
                                                    {
                                                        "version_value": "python 3.5.6"
                                                    },
                                                    {
                                                        "version_value": "python 3.7.0"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "[UNKNOWN]"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "python before versions 2.7.15, 3.4.9, 3.5.6rc1, 3.6.5rc1 and 3.7.0 is vulnerable to catastrophic backtracking in pop3lib's apop() method. An attacker could use this flaw to cause denial of service."
                        }
                    ]
                },
                "impact": {
                    "cvss": [
                        [
                            {
                                "vectorString": "4.3/CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
                                "version": "3.0"
                            }
                        ]
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "CWE-20"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "DSA-4306",
                            "refsource": "DEBIAN",
                            "url": "https://www.debian.org/security/2018/dsa-4306"
                        },
                        {
                            "name": "1042001",
                            "refsource": "SECTRACK",
                            "url": "http://www.securitytracker.com/id/1042001"
                        },
                        {
                            "name": "[debian-lts-announce] 20180926 [SECURITY] [DLA 1520-1] python3.4 security update",
                            "refsource": "MLIST",
                            "url": "https://lists.debian.org/debian-lts-announce/2018/09/msg00031.html"
                        },
                        {
                            "name": "https://bugs.python.org/issue32981",
                            "refsource": "CONFIRM",
                            "url": "https://bugs.python.org/issue32981"
                        },
                        {
                            "name": "USN-3817-2",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/3817-2/"
                        },
                        {
                            "name": "https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-release-candidate-1",
                            "refsource": "CONFIRM",
                            "url": "https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-release-candidate-1"
                        },
                        {
                            "name": "https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-6-release-candidate-1",
                            "refsource": "CONFIRM",
                            "url": "https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-6-release-candidate-1"
                        },
                        {
                            "name": "RHSA-2018:3505",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2018:3505"
                        },
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1060",
                            "refsource": "CONFIRM",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-1060"
                        },
                        {
                            "name": "RHSA-2018:3041",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2018:3041"
                        },
                        {
                            "name": "DSA-4307",
                            "refsource": "DEBIAN",
                            "url": "https://www.debian.org/security/2018/dsa-4307"
                        },
                        {
                            "name": "USN-3817-1",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/3817-1/"
                        },
                        {
                            "name": "[debian-lts-announce] 20180925 [SECURITY] [DLA 1519-1] python2.7 security update",
                            "refsource": "MLIST",
                            "url": "https://lists.debian.org/debian-lts-announce/2018/09/msg00030.html"
                        },
                        {
                            "name": "FEDORA-2019-6e1938a3c5",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JSKPGPZQNTAULHW4UH63KGOOUIDE4RRB/"
                        },
                        {
                            "name": "FEDORA-2019-cf725dd20b",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AEZ5IQT7OF7Q2NCGIVABOWYGKO7YU3NJ/"
                        },
                        {
                            "name": "FEDORA-2019-51f1e08207",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/46PVWY5LFP4BRPG3BVQ5QEEFYBVEXHCK/"
                        },
                        {
                            "name": "RHBA-2019:0327",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHBA-2019:0327"
                        },
                        {
                            "name": "RHSA-2019:1260",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:1260"
                        },
                        {
                            "name": "https://support.hpe.com/hpsc/doc/public/display?docLocale=en_US&docId=emr_na-hpesbst03951en_us",
                            "refsource": "CONFIRM",
                            "url": "https://support.hpe.com/hpsc/doc/public/display?docLocale=en_US&docId=emr_na-hpesbst03951en_us"
                        },
                        {
                            "name": "RHSA-2019:3725",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:3725"
                        },
                        {
                            "name": "https://www.oracle.com/security-alerts/cpujan2020.html",
                            "refsource": "MISC",
                            "url": "https://www.oracle.com/security-alerts/cpujan2020.html"
                        },
                        {
                            "name": "openSUSE-SU-2020:0086",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2018-1060",
        "datePublished": "2018-06-18T14:00:00",
        "dateReserved": "2017-12-04T00:00:00",
        "dateUpdated": "2020-01-21T21:06:22",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}